#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class set_ui():
    def __init__(self):
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.label = QtWidgets.QLabel("AVID: ",self)
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox("视频类型选择",self)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.rad_video = QtWidgets.QRadioButton("普通视频",self.groupBox)
        self.horizontalLayout_5.addWidget(self.rad_video)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.rad_acg = QtWidgets.QRadioButton("番剧",self.groupBox)
        self.horizontalLayout_5.addWidget(self.rad_acg)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.qd = QtWidgets.QPushButton("确定",self)
        self.verticalLayout.addWidget(self.qd)
        self.qx = QtWidgets.QPushButton("退出",self)
        self.verticalLayout.addWidget(self.qx)
        self.get_cover = QtWidgets.QPushButton("下载封面(番剧下无效)",self)
        self.verticalLayout.addWidget(self.get_cover)
        self.groupBox_2 = QtWidgets.QGroupBox("清晰度选择",self)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.rad_360 = QtWidgets.QRadioButton("360P清晰度",self.groupBox_2)
        self.horizontalLayout_6.addWidget(self.rad_360)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.rad_460 = QtWidgets.QRadioButton("460P清晰度",self.groupBox_2)
        self.horizontalLayout_6.addWidget(self.rad_460)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.rad_720 = QtWidgets.QRadioButton("720P清晰度",self.groupBox_2)
        self.horizontalLayout_6.addWidget(self.rad_720)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.rad_1080 = QtWidgets.QRadioButton("1080P清晰度",self.groupBox_2)
        self.horizontalLayout_6.addWidget(self.rad_1080)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox_3 = QtWidgets.QGroupBox("杂项",self)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.rad_tr = QtWidgets.QRadioButton("不进行转换(默认进行转换)",self.groupBox_3)
        self.horizontalLayout_7.addWidget(self.rad_tr)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.rad_del = QtWidgets.QRadioButton("转换后不删除源文件",self.groupBox_3)
        self.horizontalLayout_7.addWidget(self.rad_del)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
